name: ripe
description: Control your plants the IoT way
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  drift: ^2.19.0
  executor: ^2.2.3
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.1+1
  flutter_native_timezone_updated_gradle: ^2.0.3
  go_router: ^14.2.0
  http: ^1.2.1
  image: ^4.2.0
  image_cropper: ^7.1.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  mqtt_client: 10.3.0
  mrx_charts:
    git:
      url: git@github.com:knusperkrone/mrx-flutter-charts.git
      ref: memory_leaks
  mutex: ^3.1.0
  palette_generator: ^0.3.2+3
  path_provider: ^2.1.3
  scidart: ^0.0.2-dev.12
  shared_preferences: ^2.2.3
  sqlite3_flutter_libs: ^0.5.24
  synchronized: ^3.1.0+1
  tuple: ^2.0.2
  workmanager: ^0.5.2

dev_dependencies:
  build_runner: ^2.4.11
  drift_dev: ^2.13.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon.png
