name: ripe
description: Control your plants the IoT way

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.0
  fab_circular_menu: ^1.0.2
  flutter:
    sdk: flutter
  flutter_native_timezone: ^2.0.0
  flutter_slidable: ^0.6.0
  image: ^3.0.2
  image_cropper: ^1.4.1
  image_picker: ^0.8.0+4
  intl: ^0.17.0
  json_annotation: ^4.0.1
  mqtt_client: ^9.3.1
  palette_generator: ^0.3.0
  path_provider: ^2.0.2
  sentry_flutter: ^5.1.0
  shared_preferences: ^2.0.6
  synchronized: ^3.0.0
  tuple: ^2.0.0
  url_launcher: ^6.0.6

dev_dependencies:
  build_runner: ^2.0.4
  json_serializable: ^4.1.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon.png
