name: ripe
description: Control your plants the IoT way

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  drift: ^2.14.0
  executor: ^2.2.3
  flutter:
    sdk: flutter
  flutter_native_timezone: ^2.0.0
  http: ^1.1.2
  image: ^4.1.3
  image_cropper: ^5.0.1
  image_picker: ^1.0.6
  intl: ^0.19.0
  json_annotation: ^4.8.1
  mqtt_client: 10.0.1
  mrx_charts:
    git:
      url: git@github.com:knusperkrone/mrx-flutter-charts.git
      ref: memory_leaks
  palette_generator: ^0.3.2+3
  path_provider: ^2.1.1
  scidart: ^0.0.2-dev.12
  shared_preferences: ^2.2.2
  sqlite3_flutter_libs: ^0.5.18
  synchronized: ^3.1.0+1
  tuple: ^2.0.2

dev_dependencies:
  build_runner: ^2.4.6
  drift_dev: ^2.13.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon.png
