name: ripe
description: Control your plants the IoT way

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  fab_circular_menu: ^1.0.2
  flutter:
    sdk: flutter
  flutter_native_timezone: ^2.0.0
  http: ^0.13.5
  image: ^4.0.10
  image_cropper: ^3.0.1
  image_picker: ^0.8.6
  intl: ^0.18.0
  json_annotation: ^4.7.0
  mqtt_client: ^9.7.4
  palette_generator: ^0.3.2+2
  path_provider: ^2.0.11
  shared_preferences: ^2.0.16
  synchronized: ^3.0.1
  tuple: ^2.0.1
  url_launcher: ^6.1.7

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon.png
